bind = '[::1]:8080'

[mysql]
host = '[::1]:3306'
user = 'www'
password = ''
schema = 'www'

[site]
static_domain = 'static.flowerinsnow.cn'
www_domain = 'www.flowerinsnow.cn'
blog_url = 'https://blog.flowerinsnow.cn/'
title = '编程学习与笔记日记'
icp_number = '苏ICP备2023048510号-2'
nismsp_number = '苏公网安备32050502011681号'
