bind = '[::1]:8080'

static_domain = 'static.flowerinsnow.online'
www_domain = 'www.flowerinsnow.online'
blog_url = 'https://blog.flowerinsnow.online/'

[mysql]
host = 'localhost:3306'
user = 'www'
password = 'my-password'
schema = 'www'